trainer: 
  _target_: lightning.pytorch.trainer.Trainer
  accelerator: cpu
  devices: 1

scheduler:
  _target_: src.callbacks.scheduler.Scheduler
  n_fading_epochs: 10
  epochs_per_stage: 20
  n_stages: ${model.params.n_stages}