defaults:
  - optimizer: adam
  - training: quick
  - model: deep4net
  - preprocessing: standard
  - dataset: default_dataset
  - split: holdout
  - augmentation: default
  - _self_
hydra:
  run:
    dir: 'solution/trained_models/${model._name_}/${now:%Y-%m-%d-%H-%M-%S}'
  output_subdir: '.'