wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  name: ${now:%Y-%m-%d-%H-%M-%S}
  offline: False
  id: null # pass correct id to resume experiment!
  project: "EEG-GAN"
  log_model: False # upload lightning ckpts
  save_dir: ${output_dir/wandb_logs}
