defaults:
  - _self_
  - data: clinical
  - model: standard
  - callbacks: default
  - trainer: SLURM
  - logger: wandb

hydra:
  run:
    dir: 'trained_models/${now:%Y-%m-%d-%H-%M-%S}'
  output_subdir: '.'

train: True