defaults:
  - _self_
  - trainer: SLURM
  - data: HGD_clinical
  - model: baseline
  - callbacks: default
  - logger: wandb
output_dir: trained_models/${hydra.run.dir}
train: True

record_memory: False
