hydra:
  run:
    dir: 'trained_models/${now:%Y-%m-%d-%H-%M-%S}'
  output_subdir: '.'

defaults:
  - _self_
  - trainer: SLURM
  - data: HGD_clinical_ZCAW_normalized
  - model: baseline
  - callbacks: default
  - logger: wandb

train: True

record_memory: False